apiVersion: v1  # Specifies the API version for the Service resource.
kind: Service  # Defines the kind of Kubernetes object, which is a Service.
metadata:
  name: testwatch-nginx-service  # Name of the Service.
spec:
  selector:  # Specifies the pods that this Service targets.
    app: testwatch-nginx  # Matches pods with the label "app=testwatch-nginx".
  ports:  # Specifies the ports that the Service will expose.
  - protocol: TCP  # Protocol for the first port (TCP).
    port: 8000  # Port exposed by the Service.
    targetPort: 8000  # Port on the target pod that the Service maps to.
  - protocol: TCP  # Protocol for the second port (TCP).
    port: 80  # Port exposed by the Service.
    targetPort: 80  # Port on the target pod that the Service maps to.
  type: ClusterIP  # Type of Service, which exposes the Service only within the cluster.
