apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: default
spec:
  addresses:
  # 192.168.97.0/24
  - 192.168.97.50-192.168.97.60
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: default
spec:
  ipAddressPools:
  - first-pool


# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   namespace: metallb-system
#   name: first-pool
# spec:
#   addresses:
#     - 192.168.97.50-192.168.97.60
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   namespace: metallb-system
#   name: example
# spec:
#   ipAddressPools:
#     - first-pool
