apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  table.sql: |
    CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL
    );
