services:
  test-watch-kube-test:
    container_name: app-web-kube
    # this volume is same as the develo watch, but using watch is better
    # volumes:
    #   - "../DockerComposeWatchTest:/app"
    build: .
    develop:
      watch:
      # can you use this  - action: sync+restart but it will restart the service every time just use --reload on the dockerfile
        - action: sync
          path: ../kube_Example
          target: /app
         
    expose:
      - 8080

  nginxserver-kube-test:
    image: nginx:latest
    container_name: ngnixserver-kube
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  

  db-kube-test:
    image: postgres:latest
    container_name: postgres-db-kube
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123123
      - POSTGRES_DB=postgres
    # ports:
    #   - "5432:5432"
    # restart: unless-stopped
    # volumes:
    #   - ./CREATE_ALL_TABLE.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 120s
      timeout: 5s
      retries: 5

