apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==   # Base64-encoded password
  POSTGRES_USER: bXl1c2Vy             # Base64-encoded username
  POSTGRES_DB: bXlkYXRhYmFzZQ==       # Base64-encoded database name
