apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: MTIzMTIzMTIz   
  POSTGRES_USER: cG9zdGdyZXM=             
  POSTGRES_DB: cG9zdGdyZXM=      
  POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==
