apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: MTIzMTIzMTIz   # Base64-encoded password
  POSTGRES_USER: cG9zdGdyZXM=             # Base64-encoded username
  POSTGRES_DB: cG9zdGdyZXM=       # Base64-encoded database name
