services:
  testwatch:
    container_name: Test_Docker_Watch
    # this volume is same as the develo watch
    # volumes:
    #   - "../DockerComposeWatchTest:/app"
    build: .
    develop:
      watch:
        - action: sync
          path: ../DockerComposeWatchTest
          target: /app
          # ignore:
          #   - node_modules/
        # - action: rebuild
        #   path: package.json
    ports:
      - 8000:8000
    # command: ["uvicorn","main:app","--host","0.0.0.0","--port", "8000","--reload"]

