services:
  testwatch:
    container_name: Test_Docker_Watch
    build: .
    develop:
      watch:
        - action: rebuild
          path: ./DockerComposeWatchTest
          target: /app
          # ignore:
          #   - node_modules/
         

    ports:
      - 8000:8000
